[workspace]
members = [ "serialize",
    "verifier",
]

resolver = "2"

[workspace.dependencies]
rand = { version = "0.8.5" }
rand_chacha = { version = "0.3" }
ff = { version = "0.12.0", default-features = false }
group = "0.12" 
halo2_proofs = { path = "../halo2-nostd/halo2_proofs" }
halo2curves = { git = 'https://github.com/contrun/halo2curves.git', branch = "v0.3.1-no-std", default-features = false }
