[package]
name = "halo2-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
hex-literal = { version = "0.4.1", optional = true }

substrate-bn = "0.6.0"
serde_json = { version = "1.0.117", optional = true, default-features = false }
# halo2_proofs = { git = "https://github.com/nulltea/halo2-nostd.git", branch = "no_std" }
halo2_proofs = { path = "../halo2-nostd/halo2_proofs" }
ff = { version = "0.12.0", default-features = false }
group = "0.12" 
rand_core = { version = "0.6", default-features = false }
num-traits = "0.2"


[dev-dependencies]
hex-literal = { version = "0.4.1" }
rand = { version = "0.8.5" }
rand_chacha = { version = "0.3" }
serde_json = { version = "1.0.117" }
